# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: kahi
    main: ./cmd/kahi
    binary: kahi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/kahiteam/kahi/internal/version.Version={{.Version}}
      - -X github.com/kahiteam/kahi/internal/version.Commit={{.Commit}}
      - -X github.com/kahiteam/kahi/internal/version.Date={{.Date}}

  - id: kahi-fips
    main: ./cmd/kahi
    binary: kahi-fips
    env:
      - CGO_ENABLED=0
      - GOFIPS140=v1.0.0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/kahiteam/kahi/internal/version.Version={{.Version}}
      - -X github.com/kahiteam/kahi/internal/version.Commit={{.Commit}}
      - -X github.com/kahiteam/kahi/internal/version.Date={{.Date}}
      - -X github.com/kahiteam/kahi/internal/version.FIPS=true

archives:
  - id: kahi
    ids:
      - kahi
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: kahi-fips
    ids:
      - kahi-fips
    name_template: "{{ .ProjectName }}-fips_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: kahiteam
    name: kahi
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
